name = "pet-care-app"
compatibility_date = "2026-01-31"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]
pages_build_output_dir = "dist"

[env.production]
vars = { NODE_ENV = "production" }
